### ISSUE TITLE
404 trying to fetch phone book

### ISSUE THREAD

**Issue by brianjmurrell** [EionRobb/pidgin-pushbullet#17] opened 2016-12-09 14:17 UTC
When trying to log on to PB I'm getting back from the server:

```
(09:15:54) pushbullet: Got response: {"accounts":[],"blocks":[],"channels":[],"chats":[],"clients":[],"contacts":[],"devices":[],"grants":[],"pushes":[],"profiles":[],"subscriptions":[],"texts":[]}
(09:15:54) util: Response headers: 'HTTP/1.0 404 Not Found
Content-Type: application/json; charset=utf-8
X-Cloud-Trace-Context: 68398aa6e6198f72b16b5b802d1857a4
Date: Fri, 09 Dec 2016 14:15:54 GMT
Server: Google Frontend
Content-Length: 155
```

I believe that is in response to trying to fetch the ```phonebook_...``` resource from PB.

**Comment by apippin** [comment] 2017-03-27 21:42
I ran into the same issue and filed it as #19. My new issue was a duplicate of this issue. However, I was able to push up a fix for it and it was merged into master. Therefore, closing this out as that fix should address this issue.

**Closed as completed by apippin** 2017-03-27 21:42 UTC

**Comment by brianjmurrell** [comment] 2017-03-28 16:02
Confirming that master on cd33d32f5f0a7ee90fff547265b0ba80d165046d is now working for me.

**Comment by synthead** [comment] 2017-04-18 03:59
Just want to say that I love seeing the recent commits!  The plugin is working for me now and having native SMS integration with Pidgin is something I've been waiting for for a long time.  Thanks so much!
